<?php
    include('navbar.php');
    $connection = mysqli_connect("localhost", "root", "", "assignment") or die(mysql_error());
    $id = $_REQUEST['id'];
    $query = "SELECT * FROM internships " . "where id like '$id'";
    $results = mysqli_query($connection, $query) or die(mysql_error());
    $row = mysqli_fetch_assoc($results);
    extract($row); 
    echo "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"5px\">";
    echo "<tr><td style=\"padding: 3px;\" rowspan=\"6\">";
    echo "<td colspan=\"2\" align=\"center\" style=\"font-family:verdana; font-size: 150%;\"><b>";
    echo $title;
    echo "</b></td></tr><tr><td colspan=\"2\"><table><tr><td>";
    $title = urlencode($title);
    // $pfquery = "select feature1, feature2, feature3, feature4, feature5, feature6 from productfeatures " . "where item_code like '$code'";
    // $pfresults = mysqli_query($connection, $pfquery) or die(mysql_error());
    // $pfrow = mysqli_fetch_assoc($pfresults);
    // extract($pfrow);
    // echo $feature1;
    // echo "</td><td>";
    // echo $feature2;
    // echo "</td><td>";
    // echo $feature3;
    // echo "</td><td>";
    // echo $feature4;
    // echo "</td></tr><tr><td>";
    // echo $feature5;
    // echo "</td><td>";
    // echo $feature6;
    echo "</td></tr><tr>";
    // echo "<form method=\"post\" action=\"cart.php?action=add&icode=$item_code&iname=$itemname&iprice=$itemprice\">";
    echo "<td colspan=\"2\" style=\"font-family:verdana; font-size: 150%;\">";
    // echo " Quantity: <input type=\"text\" name=\"quantity\" size=\"10\">&nbsp;&nbsp;&nbsp;Price: " . $itemprice;
    echo "</td></tr><tr><td colspan=\"2\"><input type=\"submit\" name=\"apply\" value=\"Apply\" style=\"font-size: 150%;\"></td>";
    // echo " </form>";
    echo "</tr></table></table>";
    echo "<p style=\"font-size:140%;\">Description</p>";
    echo $description;
?>